channels:
- defaults
dependencies:
- python=3.9.19
- pip:
  - anyio==4.3.0
  - argon2-cffi==23.1.0
  - argon2-cffi-bindings==21.2.0
  - arrow==1.3.0
  - asttokens 
  - async-lru==2.0.4
  - attrs==23.2.0
  - Babel==2.14.0
  - backcall
  - beautifulsoup4==4.12.3
  - bleach==6.1.0
  - Bottleneck 
  - Brotli 
  - certifi 
  - cffi==1.16.0
  - charset-normalizer 
  - cloudpickle==3.0.0
  - colorama 
  - comm 
  - contourpy
  - cycler 
  - debugpy
  - decorator
  - defusedxml==0.7.1
  - exceptiongroup==1.2.1
  - executing 
  - fastjsonschema==2.19.1
  - fonttools 
  - fqdn==1.5.1
  - getenv==0.2.0
  - h11==0.14.0
  - httpcore==1.0.5
  - httpx==0.27.0
  - idna 
  - importlib-resources 
  - importlib_metadata
  - ipykernel 
  - ipython 
  - isoduration==20.11.0
  - jedi 
  - Jinja2==3.1.3
  - joblib 
  - json5==0.9.25
  - jsonpointer==2.4
  - jsonschema==4.21.1
  - jsonschema-specifications==2023.12.1
  - jupyter-events==0.10.0
  - jupyter-lsp==2.2.5
  - jupyter_client 
  - jupyter_core 
  - jupyter_server==2.14.0
  - jupyter_server_terminals==0.5.3
  - jupyterlab==4.1.8
  - jupyterlab_pygments==0.3.0
  - jupyterlab_server==2.27.1
  - kiwisolver
  - llvmlite==0.42.0
  - MarkupSafe==2.1.5
  - matplotlib 
  - matplotlib-inline 
  - missingno==0.5.2
  - mistune==3.0.2
  - mkl-fft 
  - mkl-random 
  - mkl-service==2.4.0
  - mlxtend==0.23.1
  - nbclient==0.10.0
  - nbconvert==7.16.4
  - nbformat==5.10.4
  - nest_asyncio
  - notebook_shim==0.2.4
  - numba==0.59.1
  - numexpr
  - numpy 
  - overrides==7.7.0
  - packaging 
  - pandas 
  - pandocfilters==1.5.1
  - parso 
  - pickleshare 
  - pillow 
  - prometheus_client==0.20.0
  - prompt-toolkit 
  - psutil 
  - pure-eval 
  - pycparser==2.22
  - Pygments 
  - pyparsing 
  - PySocks 
  - python-dateutil 
  - python-json-logger==2.0.7
  - pytz 
  - pywin32==227
  - pywinpty==2.0.13
  - PyYAML==6.0.1
  - pyzmq 
  - referencing==0.35.0
  - requests 
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rpds-py==0.18.0
  - scikit-learn 
  - scipy 
  - seaborn 
  - Send2Trash==1.8.3
  - shap==0.45.0
  - sidetable==0.9.1
  - six 
  - slicer==0.0.7
  - sniffio==1.3.1
  - soupsieve==2.5
  - stack-data 
  - terminado==0.18.1
  - threadpoolctl 
  - tinycss2==1.3.0
  - tomli==2.0.1
  - tornado 
  - tqdm==4.66.2
  - traitlets 
  - types-python-dateutil==2.9.0.20240316
  - typing_extensions 
  - tzdata 
  - unicodedata2 
  - uri-template==1.3.0
  - urllib3 
  - wcwidth 
  - webcolors==1.13
  - webencodings==0.5.1
  - websocket-client==1.8.0
  - win-inet-pton 
  - zipp 
name: lighthouse_env
